apiVersion: v1
kind: Secret
metadata:
  name: bedrock-secret
  namespace: agentgateway-system
  labels:
    app.kubernetes.io/managed-by: agentic-demo
    agentgateway.dev/provider: bedrock
type: Opaque
stringData:
  accessKey: ''
  secretKey: ''
