import { AddonFeature } from '../../src/lib/feature.js';
import { KubernetesHelper, CommandRunner } from '../../src/lib/common.js';
import {
  CERTS_WORK_DIR as ISTIO_CACERTS_WORK_DIR,
  SPIRE_DISTINCT_ROOTS_DIR,
} from '../../src/lib/multicluster.js';
import { join } from 'path';
import { tmpdir } from 'os';
import { existsSync, mkdirSync, readFileSync, writeFileSync, unlinkSync, readdirSync } from 'fs';
import yaml from 'js-yaml';

const SPIRE_HELM_REPO_NAME = 'spire';
const SPIRE_HELM_REPO_URL = 'https://spiffe.github.io/helm-charts-hardened/';
const SPIRE_CERTS_WORK_DIR = join(tmpdir(), 'agentic-spire-certs');

const VALID_CERT_MODES = ['self-signed', 'cert-manager', 'manual'];

/**
 * SPIRE Addon Feature
 *
 * SPIRE server + agents for workload identity in Istio Ambient. Pre-phase addon
 * (runs before istiod/ztunnel). Ref: https://docs.solo.io/istio/1.30.x/ambient/security/spire/
 *
 * Configuration:
 * {
 *   spireNamespace: string,     // Default: 'spire-server'
 *   trustDomain: string,        // Default: cluster.name
 *   spireVersion: string,       // Default: '0.30.0'
 *   spireCrdsVersion: string,   // Default: '0.6.0'
 *   certMode: string,           // 'self-signed' | 'cert-manager' | 'manual'
 *   certs: {                    // manual mode only
 *     caCert: string,           // Path to intermediate CA cert
 *     caKey: string,            // Path to intermediate CA private key
 *     caChain: string,          // Path to cert chain (intermediate + root)
 *   },
 *   certManager: {              // cert-manager mode only
 *     issuerRef: {
 *       name: string,           // Default: 'selfsigned-issuer'
 *       kind: string,           // Default: 'ClusterIssuer'
 *     }
 *   },
 *   multiRoot: boolean,         // Default: false. self-signed only. SPIRE keeps its own root
 *                               // instead of reusing istiod cacerts' shared root; both roots
 *                               // federate into each other's bundle so either is trusted.
 *   distinctRoots: boolean,     // Default: false. self-signed only. Implies multiRoot. Each
 *                               // cluster gets its own root, pre-generated by SpireRootManager
 *                               // before any install (deploy() throws if missing). Every peer
 *                               // root is added to this cluster's SPIRE bundle and cacerts as
 *                               // an independent anchor - not cross-signed, just listed.
 * }
 *
 * self-signed and cert-manager modes stamp the intermediate CA cert with a trustDomain SAN
 * (DNS + SPIFFE URI), required by ztunnel's VALIDATE_SPIFFE_TRUST_DOMAIN_NAMES=STRICT chain
 * verification. manual mode's CA must carry the same SAN itself.
 */
export class SpireFeature extends AddonFeature {
  constructor(name, config) {
    super(name, config);
    this.spireNamespace = config.spireNamespace || 'spire-server';
    this.trustDomain = config.trustDomain || config.clusterName || 'cluster.local';
    this.spireVersion = config.spireVersion || '0.30.0';
    this.spireCrdsVersion = config.spireCrdsVersion || '0.6.0';
    this.certMode = config.certMode || 'self-signed';
    this.certs = config.certs || null;
    this.certManager = config.certManager || {};
    this.distinctRoots = config.distinctRoots === true;
    this.multiRoot = config.multiRoot === true || this.distinctRoots;
    this.kubeContext = config.kubeContext || null;
  }

  validate() {
    if (!VALID_CERT_MODES.includes(this.certMode)) {
      throw new Error(
        `Invalid certMode '${this.certMode}'. Must be: ${VALID_CERT_MODES.join(', ')}`
      );
    }
    if (this.certMode === 'manual') {
      if (!this.certs?.caCert || !this.certs?.caKey || !this.certs?.caChain) {
        throw new Error('manual certMode requires certs.caCert, certs.caKey, and certs.caChain');
      }
    }
    return true;
  }

  get certsWorkDir() {
    return SPIRE_CERTS_WORK_DIR;
  }

  get certManagerIssuerRef() {
    return {
      name: this.certManager?.issuerRef?.name || 'selfsigned-issuer',
      kind: this.certManager?.issuerRef?.kind || 'ClusterIssuer',
    };
  }

  /** Issue an intermediate CA via cert-manager. Requires the issuer to already exist. */
  async #prepareCertManagerCerts(context) {
    this.log('Preparing SPIRE CA certificates (cert-manager)...', 'info');
    const issuerRef = this.certManagerIssuerRef;
    const certName = 'spire-upstream-ca';
    const secretName = 'spire-upstream-ca-cm';

    const certificate = {
      apiVersion: 'cert-manager.io/v1',
      kind: 'Certificate',
      metadata: { name: certName, namespace: this.spireNamespace },
      spec: {
        secretName,
        duration: '87600h',
        renewBefore: '720h',
        isCA: true,
        commonName: `SPIRE Intermediate CA - ${this.trustDomain}`,
        subject: { organizations: ['SPIRE'] },
        // required for ztunnel's VALIDATE_SPIFFE_TRUST_DOMAIN_NAMES=STRICT chain verification
        dnsNames: [this.trustDomain],
        uris: [`spiffe://${this.trustDomain}`],
        issuerRef: { name: issuerRef.name, kind: issuerRef.kind, group: 'cert-manager.io' },
        secretTemplate: { labels: { 'spire.io/upstream-ca': 'true' } },
        privateKey: { algorithm: 'RSA', size: 2048 },
      },
    };

    await this.applyResource(certificate, context);
    this.log(`Waiting for cert-manager secret '${secretName}'...`, 'info');
    await this.#waitForSecret(secretName, this.spireNamespace, context);

    // exec to capture stdout
    const ctxFlag = context ? `--context=${context}` : '';
    const result = await CommandRunner.exec(
      `kubectl ${ctxFlag} get secret ${secretName} -n ${this.spireNamespace} -o jsonpath={.data}`,
      { ignoreError: false }
    );
    const data = JSON.parse(result.stdout || '{}');
    const caCert = Buffer.from(data['tls.crt'] || '', 'base64').toString('utf8');
    const caKey = Buffer.from(data['tls.key'] || '', 'base64').toString('utf8');

    // newer cert-manager puts the full chain in ca.crt; fall back to tls.crt if absent
    const caBundle = data['ca.crt']
      ? Buffer.from(data['ca.crt'], 'base64').toString('utf8')
      : caCert;

    await this.#createUpstreamCaSecret(caCert, caKey, this.#extractRootCert(caBundle), context);
    this.log('SPIRE upstream CA secret created via cert-manager', 'success');
    return caBundle;
  }

  /** Read user-provided cert files into the SPIRE upstream CA secret. */
  async #prepareManualCerts(context) {
    this.log('Preparing SPIRE CA certificates (manual)...', 'info');
    const caCert = readFileSync(this.certs.caCert, 'utf8');
    const caKey = readFileSync(this.certs.caKey, 'utf8');
    const caBundle = readFileSync(this.certs.caChain, 'utf8');
    await this.#createUpstreamCaSecret(caCert, caKey, this.#extractRootCert(caBundle), context);
    this.log('SPIRE upstream CA secret created from manual certs', 'success');
    return caBundle;
  }

  /**
   * Last cert in a PEM chain (the root). SPIRE's bundle_file_path publishes root-only -
   * peers present their own intermediate, so a root-only bundle is a complete trust anchor.
   */
  #extractRootCert(pemChain) {
    const certs =
      pemChain.match(/-----BEGIN CERTIFICATE-----[\s\S]+?-----END CERTIFICATE-----/g) || [];
    if (certs.length === 0) {
      throw new Error('No PEM certificates found while extracting SPIRE trust bundle root');
    }
    return certs[certs.length - 1] + '\n';
  }

  /**
   * Generate/reuse a root CA and per-cluster intermediate.
   * Secret spiffe-upstream-ca: tls.crt / tls.key / bundle.crt
   */
  async #prepareSelfSignedCerts(context) {
    this.log('Preparing SPIRE CA certificates (self-signed)...', 'info');
    mkdirSync(SPIRE_CERTS_WORK_DIR, { recursive: true });

    // Reuse istiod's cacerts root when present (multicluster) so SPIRE and istiod
    // intermediates are mutually trusted without federation; else SPIRE-only root.
    const sharedRootKeyPath = join(ISTIO_CACERTS_WORK_DIR, 'root-key.pem');
    const sharedRootCertPath = join(ISTIO_CACERTS_WORK_DIR, 'root-cert.pem');
    const usingSharedRoot =
      !this.multiRoot && existsSync(sharedRootKeyPath) && existsSync(sharedRootCertPath);

    let rootKeyPath, rootCertPath;
    if (usingSharedRoot) {
      rootKeyPath = sharedRootKeyPath;
      rootCertPath = sharedRootCertPath;
    } else if (this.distinctRoots) {
      const ownRootDir = join(SPIRE_DISTINCT_ROOTS_DIR, this.trustDomain.replace(/\//g, '-'));
      rootKeyPath = join(ownRootDir, 'root-key.pem');
      rootCertPath = join(ownRootDir, 'root-cert.pem');
      if (!existsSync(rootKeyPath) || !existsSync(rootCertPath)) {
        throw new Error(
          `distinctRoots is enabled but no pre-generated root exists for trust domain ` +
            `'${this.trustDomain}'. SpireRootManager must run before cluster installs.`
        );
      }
    } else {
      rootKeyPath = join(SPIRE_CERTS_WORK_DIR, 'root-key.pem');
      rootCertPath = join(SPIRE_CERTS_WORK_DIR, 'root-cert.pem');
    }
    const clusterDir = join(SPIRE_CERTS_WORK_DIR, this.trustDomain.replace(/\//g, '-'));
    mkdirSync(clusterDir, { recursive: true });

    const caKeyPath = join(clusterDir, 'ca.key');
    const caCsrPath = join(clusterDir, 'ca.csr');
    const caCertPath = join(clusterDir, 'ca.crt');
    const caBundlePath = join(clusterDir, 'ca-chain.pem');
    const extFilePath = join(clusterDir, 'ca-ext.cnf');

    if (usingSharedRoot) {
      this.log('Reusing shared root CA from istiod cacerts to sign SPIRE intermediate', 'info');
    } else if (this.distinctRoots) {
      this.log(`Using pre-generated independent root for '${this.trustDomain}'`, 'info');
    } else if (!existsSync(rootKeyPath)) {
      this.log('Generating shared SPIRE root CA...', 'info');
      await CommandRunner.exec(`openssl genrsa -out "${rootKeyPath}" 2048`);
      await CommandRunner.exec(
        `openssl req -new -x509 -days 3650 -key "${rootKeyPath}" ` +
          `-out "${rootCertPath}" -subj "/CN=SPIRE Root CA"`
      );
    } else {
      this.log('Shared SPIRE root CA already exists, reusing', 'info');
    }

    this.log(`Generating intermediate CA for trust domain '${this.trustDomain}'...`, 'info');

    // SAN on the intermediate CA itself (not just the leaf SVID) - ztunnel's
    // VALIDATE_SPIFFE_TRUST_DOMAIN_NAMES=STRICT walks the chain for an ancestor SAN
    // matching the trust domain.
    writeFileSync(
      extFilePath,
      '[req]\ndistinguished_name = req_distinguished_name\n' +
        'req_extensions = v3_req\nprompt = no\n' +
        '[req_distinguished_name]\nCN = SPIRE Intermediate CA\n' +
        '[v3_req]\nkeyUsage = critical, keyCertSign, cRLSign\n' +
        'basicConstraints = critical, CA:true, pathlen:1\n' +
        'subjectKeyIdentifier = hash\n' +
        `subjectAltName = DNS:${this.trustDomain}, URI:spiffe://${this.trustDomain}\n`
    );

    await CommandRunner.exec(`openssl genrsa -out "${caKeyPath}" 2048`);
    await CommandRunner.exec(
      `openssl req -new -key "${caKeyPath}" -out "${caCsrPath}" ` +
        `-config "${extFilePath}" -subj "/CN=SPIRE Intermediate CA"`
    );
    await CommandRunner.exec(
      `openssl x509 -req -in "${caCsrPath}" -CA "${rootCertPath}" -CAkey "${rootKeyPath}" ` +
        `-CAcreateserial -out "${caCertPath}" -days 1825 -extensions v3_req -extfile "${extFilePath}"`
    );

    const rootCert = readFileSync(rootCertPath, 'utf8');
    const intermediateCert = readFileSync(caCertPath, 'utf8');

    // Full chain (intermediate + root) to federate into Istio cacerts (#federateWithIstioCA),
    // independent of what SPIRE publishes via bundle_file_path (root only, #extractRootCert).
    const caBundle = intermediateCert + rootCert;
    writeFileSync(caBundlePath, caBundle);

    // Multi-root: fold istiod's cacerts root into SPIRE's published bundle so ambient
    // workloads (via delegated_api_client.rs, which allows multiple trust authorities)
    // trust istiod-issued peers without a common root.
    let spireBundle = rootCert;
    if (this.multiRoot) {
      const istioRoot = await this.#getIstioCARootCert(context);
      if (istioRoot && !istioRoot.includes(rootCert.trim())) {
        this.log('Multi-root mode: adding istiod cacerts root to SPIRE trust bundle', 'info');
        spireBundle = `${spireBundle.trimEnd()}\n${istioRoot}`;
      }
    }

    // Distinct-roots: each peer root is an independent anchor - not cross-signed,
    // just listed alongside ours (see class JSDoc).
    const peerRoots = this.distinctRoots ? this.#discoverPeerRoots() : [];
    if (peerRoots.length > 0) {
      this.log(`Distinct-roots mode: trusting ${peerRoots.length} peer SPIRE root(s)`, 'info');
      spireBundle = `${spireBundle.trimEnd()}\n${peerRoots.join('\n')}`;
    }

    await this.#createUpstreamCaSecret(
      intermediateCert,
      readFileSync(caKeyPath, 'utf8'),
      spireBundle,
      context
    );

    this.log('SPIRE upstream CA secret created', 'success');

    // Federate into cacerts: own chain + peer roots (peers present their own
    // intermediate at handshake, so root-only suffices).
    return peerRoots.length > 0 ? `${caBundle.trimEnd()}\n${peerRoots.join('\n')}` : caBundle;
  }

  /** Every other trust domain dir under SPIRE_DISTINCT_ROOTS_DIR is a peer's root (see SpireRootManager). */
  #discoverPeerRoots() {
    if (!existsSync(SPIRE_DISTINCT_ROOTS_DIR)) return [];
    const ownDirName = this.trustDomain.replace(/\//g, '-');
    return readdirSync(SPIRE_DISTINCT_ROOTS_DIR, { withFileTypes: true })
      .filter(entry => entry.isDirectory() && entry.name !== ownDirName)
      .map(entry => join(SPIRE_DISTINCT_ROOTS_DIR, entry.name, 'root-cert.pem'))
      .filter(existsSync)
      .map(certPath => readFileSync(certPath, 'utf8').trim());
  }

  /** Create the spiffe-upstream-ca secret, overwriting any existing. */
  async #createUpstreamCaSecret(caCert, caKey, caBundle, context) {
    const ctxArgs = context ? [`--context=${context}`] : [];

    // Temp files: kubectl --from-literal handles multi-line poorly
    const tmpCert = join(tmpdir(), `spire-ca-cert-${process.pid}.pem`);
    const tmpKey = join(tmpdir(), `spire-ca-key-${process.pid}.pem`);
    const tmpBundle = join(tmpdir(), `spire-ca-bundle-${process.pid}.pem`);

    try {
      writeFileSync(tmpCert, caCert, 'utf8');
      writeFileSync(tmpKey, caKey, 'utf8');
      writeFileSync(tmpBundle, caBundle, 'utf8');

      // Idempotent: delete if present
      await KubernetesHelper.kubectl(
        [
          ...ctxArgs,
          'delete',
          'secret',
          'spiffe-upstream-ca',
          '-n',
          this.spireNamespace,
          '--ignore-not-found=true',
        ],
        { spinner: this.spinner }
      );

      await KubernetesHelper.kubectl(
        [
          ...ctxArgs,
          'create',
          'secret',
          'generic',
          'spiffe-upstream-ca',
          `-n`,
          this.spireNamespace,
          `--from-file=tls.crt=${tmpCert}`,
          `--from-file=tls.key=${tmpKey}`,
          `--from-file=bundle.crt=${tmpBundle}`,
        ],
        { spinner: this.spinner }
      );
    } finally {
      for (const f of [tmpCert, tmpKey, tmpBundle]) {
        try {
          unlinkSync(f);
        } catch {
          /* best effort */
        }
      }
    }
  }

  async #prepareCerts(context) {
    switch (this.certMode) {
      case 'self-signed':
        return this.#prepareSelfSignedCerts(context);
      case 'cert-manager':
        return this.#prepareCertManagerCerts(context);
      case 'manual':
        return this.#prepareManualCerts(context);
      default:
        throw new Error(`Unknown certMode: ${this.certMode}`);
    }
  }

  /** istiod's cacerts root-cert.pem, or null if the secret is absent. */
  async #getIstioCARootCert(context) {
    const ctxFlag = context ? `--context=${context}` : '';
    const result = await CommandRunner.exec(
      `kubectl ${ctxFlag} get secret cacerts -n istio-system -o jsonpath='{.data.root-cert\\.pem}'`,
      { ignoreError: true }
    );
    if (result.exitCode || !result.stdout) return null;
    return Buffer.from(result.stdout, 'base64').toString('utf8');
  }

  /**
   * SPIRE issues its own CA chain for ambient workloads (via ztunnel), separate from istiod's.
   * When a profile also sets spec.mesh.certificates (shared cacerts via CertificateManager),
   * istiod-issued proxies like Gateways trust only the cacerts root and can't verify a
   * SPIRE-signed peer, so a Gateway re-originating HBONE to an ambient backend fails with
   * "unable to get issuer certificate". Merging SPIRE's chain into cacerts' root-cert.pem closes
   * that gap. No-op if cacerts is absent - SPIRE-only (or istiod ephemeral CA) profiles never hit it.
   */
  async #federateWithIstioCA(context, caBundle) {
    // multiRoot/distinctRoots imply multi-cluster, where CertificateManager creates cacerts on
    // every cluster - but not barriered against this addon's deploy(), so cacerts may not exist
    // here yet. Wait rather than skip, or a slower cluster's federation is silently dropped
    // (the gap that caused a live UnknownCA cross-cluster mTLS failure).
    if (this.multiRoot || this.distinctRoots) {
      try {
        await this.#waitForSecret('cacerts', 'istio-system', context);
      } catch {
        this.log(
          'cacerts secret never appeared - skipping istiod CA federation. Cross-cluster mTLS ' +
            'between SPIRE-issued peers and istiod-issued gateways (e.g. istio-eastwest) will ' +
            "fail with 'UnknownCA' until cacerts is patched and istiod is restarted.",
          'warn'
        );
        return;
      }
    }

    const currentRootPem = await this.#getIstioCARootCert(context);
    if (!currentRootPem) return;

    if (currentRootPem.includes(caBundle.trim())) {
      this.log('Istio cacerts already trusts the SPIRE CA, skipping federation', 'info');
      return;
    }

    this.log('Federating SPIRE CA into Istio cacerts trust bundle...', 'info');
    const mergedPem = `${currentRootPem.trimEnd()}\n${caBundle}`;
    const mergedB64 = Buffer.from(mergedPem, 'utf8').toString('base64');

    await KubernetesHelper.kubectl(
      [
        ...(context ? [`--context=${context}`] : []),
        'patch',
        'secret',
        'cacerts',
        '-n',
        'istio-system',
        '--type=merge',
        '-p',
        JSON.stringify({ data: { 'root-cert.pem': mergedB64 } }),
      ],
      { spinner: this.spinner }
    );
    this.log('Istio cacerts now trusts the SPIRE CA', 'success');

    const ctxFlag = context ? `--context=${context}` : '';
    const istiod = await CommandRunner.exec(
      `kubectl ${ctxFlag} get deployment istiod -n istio-system`,
      {
        ignoreError: true,
      }
    );
    if (!istiod.exitCode) {
      this.log('Restarting istiod to pick up the federated trust bundle...', 'info');
      await KubernetesHelper.kubectl(
        [
          ...(context ? [`--context=${context}`] : []),
          'rollout',
          'restart',
          'deployment/istiod',
          '-n',
          'istio-system',
        ],
        { spinner: this.spinner }
      );
    }
  }

  async #waitForSecret(name, namespace, context, timeoutMs = 120000) {
    const ctxFlag = context ? `--context=${context}` : '';
    const start = Date.now();
    while (Date.now() - start < timeoutMs) {
      const result = await CommandRunner.exec(
        `kubectl ${ctxFlag} get secret ${name} -n ${namespace}`,
        { ignoreError: true }
      );
      if (!result.exitCode) return;
      await new Promise(resolve => setTimeout(resolve, 3000));
    }
    throw new Error(`Secret '${name}' not found in '${namespace}' within timeout`);
  }

  buildSpireHelmValues() {
    const tolerations = [
      { effect: 'NoSchedule', operator: 'Exists' },
      { key: 'CriticalAddonsOnly', operator: 'Exists' },
      { effect: 'NoExecute', operator: 'Exists' },
    ];
    return {
      global: {
        spire: { trustDomain: this.trustDomain },
      },
      'spire-agent': {
        authorizedDelegates: [`spiffe://${this.trustDomain}/ns/istio-system/sa/ztunnel`],
        sockets: {
          admin: { enabled: true, mountOnHost: true },
          hostBasePath: '/run/spire/agent/sockets',
        },
        tolerations,
      },
      'spire-server': {
        upstreamAuthority: {
          disk: {
            enabled: true,
            // secret.create is false - we create spiffe-upstream-ca ourselves (tls.crt/tls.key/
            // bundle.crt). The chart renders bundle_file_path (publishing the root in SPIRE's
            // bundle) only when secret.data.bundle is non-empty, regardless of secret.create - so
            // this placeholder is required though never used to create anything. Without it the
            // published bundle is intermediate-only, which downstream verifiers reject with
            // "unable to get issuer certificate".
            secret: {
              create: false,
              name: 'spiffe-upstream-ca',
              data: { bundle: 'externally-managed' },
            },
          },
        },
      },
      'spiffe-csi-driver': {
        tolerations,
      },
    };
  }

  async deploy() {
    this.log(`Installing SPIRE (trust domain: ${this.trustDomain})...`, 'info');

    // 1. Ensure spire-server namespace
    await this.ensureNamespace(this.spireNamespace, this.kubeContext);
    this.log(`Namespace '${this.spireNamespace}' ready`, 'info');

    // 2. Prepare upstream CA secret
    const caBundle = await this.#prepareCerts(this.kubeContext);

    // 2b. Trust SPIRE's CA from istiod's side when a shared cacerts exists
    await this.#federateWithIstioCA(this.kubeContext, caBundle);

    // 3. Add SPIRE Helm repo
    await this.#addHelmRepo();

    // 4. Install spire-crds
    await this.#installSpirecRDs();

    // 5. Install spire
    await this.#installSpire();

    // 6. Wait for SPIRE pods
    await this.#waitForSpirePods();

    // 7. Register ClusterSPIFFEIDs
    await this.#applyClusterSpiffeIDs();

    this.log('SPIRE installed successfully', 'success');
  }

  async #addHelmRepo() {
    this.log('Adding SPIRE Helm repository...', 'info');
    await CommandRunner.run('helm', ['repo', 'add', SPIRE_HELM_REPO_NAME, SPIRE_HELM_REPO_URL], {
      ignoreError: true,
    });
    await CommandRunner.run('helm', ['repo', 'update', SPIRE_HELM_REPO_NAME]);
  }

  async #installSpirecRDs() {
    this.log(`Installing spire-crds chart (${this.spireCrdsVersion})...`, 'info');
    const args = [
      'upgrade',
      '-i',
      'spire-crds',
      `${SPIRE_HELM_REPO_NAME}/spire-crds`,
      '--namespace',
      this.spireNamespace,
      '--version',
      this.spireCrdsVersion,
      '--create-namespace',
      '--wait',
    ];
    if (this.kubeContext) args.push('--kube-context', this.kubeContext);
    await KubernetesHelper.helm(args, { spinner: this.spinner });
  }

  async #installSpire() {
    this.log(`Installing spire chart (${this.spireVersion})...`, 'info');
    const valuesYaml = yaml.dump(this.buildSpireHelmValues(), { lineWidth: -1 });
    const tmpValues = join(tmpdir(), `spire-values-${process.pid}.yaml`);
    try {
      writeFileSync(tmpValues, valuesYaml, 'utf8');
      const args = [
        'upgrade',
        '-i',
        'spire',
        `${SPIRE_HELM_REPO_NAME}/spire`,
        '--namespace',
        this.spireNamespace,
        '--version',
        this.spireVersion,
        '-f',
        tmpValues,
        '--wait',
        '--timeout',
        '5m',
      ];
      if (this.kubeContext) args.push('--kube-context', this.kubeContext);
      await KubernetesHelper.helm(args, { spinner: this.spinner });
    } finally {
      try {
        unlinkSync(tmpValues);
      } catch {
        /* best effort */
      }
    }
    this.log('spire chart installed', 'info');
  }

  async #waitForSpirePods() {
    this.log('Waiting for SPIRE pods to be ready...', 'info');
    const ctxArgs = this.kubeContext ? [`--context=${this.kubeContext}`] : [];
    try {
      await KubernetesHelper.kubectl(
        [
          ...ctxArgs,
          '-n',
          this.spireNamespace,
          'wait',
          '--for=condition=Ready',
          'pods',
          '--all',
          '--timeout=300s',
        ],
        { spinner: this.spinner }
      );
    } catch (error) {
      this.log(`Warning: some SPIRE pods may not be ready: ${error.message}`, 'warn');
    }
    this.log('SPIRE pods ready', 'info');
  }

  async #applyClusterSpiffeIDs() {
    this.log('Applying ClusterSPIFFEID resources...', 'info');
    const ids = [
      {
        name: 'istio-ztunnel-reg',
        template: `spiffe://{{ .TrustDomain }}/ns/{{ .PodMeta.Namespace }}/sa/{{ .PodSpec.ServiceAccountName }}`,
        matchLabels: { app: 'ztunnel' },
      },
      {
        name: 'istio-waypoint-reg',
        template: `spiffe://{{ .TrustDomain }}/ns/{{ .PodMeta.Namespace }}/sa/{{ .PodSpec.ServiceAccountName }}`,
        matchLabels: { 'istio.io/gateway-name': 'waypoint' },
      },
      // enterprise-agentgateway-waypoint pods use 'waypoint: true', not
      // 'istio.io/gateway-name: waypoint' like native Istio waypoints. Confirmed live.
      {
        name: 'istio-agentgateway-waypoint-reg',
        template: `spiffe://{{ .TrustDomain }}/ns/{{ .PodMeta.Namespace }}/sa/{{ .PodSpec.ServiceAccountName }}`,
        matchLabels: { waypoint: 'true' },
      },
      {
        name: 'istio-ambient-reg',
        template: `spiffe://{{ .TrustDomain }}/ns/{{ .PodMeta.Namespace }}/sa/{{ .PodSpec.ServiceAccountName }}`,
        matchLabels: { 'istio.io/dataplane-mode': 'ambient' },
      },
    ];

    for (const id of ids) {
      const resource = {
        apiVersion: 'spire.spiffe.io/v1alpha1',
        kind: 'ClusterSPIFFEID',
        metadata: { name: id.name },
        spec: {
          spiffeIDTemplate: id.template,
          podSelector: { matchLabels: id.matchLabels },
        },
      };
      await this.applyResource(resource, this.kubeContext);
      this.log(`ClusterSPIFFEID '${id.name}' applied`, 'info');
    }
  }

  async cleanup() {
    this.log('Cleaning up SPIRE...', 'info');

    const ctxArgs = this.kubeContext ? [`--context=${this.kubeContext}`] : [];
    const helmCtxArgs = this.kubeContext ? ['--kube-context', this.kubeContext] : [];

    // 1. Delete ClusterSPIFFEID resources
    for (const name of [
      'istio-ambient-reg',
      'istio-waypoint-reg',
      'istio-agentgateway-waypoint-reg',
      'istio-ztunnel-reg',
    ]) {
      try {
        await KubernetesHelper.kubectl(
          [...ctxArgs, 'delete', 'clusterspiffeid', name, '--ignore-not-found=true'],
          { spinner: this.spinner }
        );
      } catch {
        // best effort
      }
    }

    // 2. Uninstall spire chart. --no-hooks skips the spiffe-oidc-discovery-provider pre-delete
    // hook Job, which can stall indefinitely (Helm then aborts uninstall after its 5m wait);
    // step 4's namespace delete removes everything anyway.
    try {
      await CommandRunner.run('helm', [
        ...helmCtxArgs,
        'uninstall',
        'spire',
        '-n',
        this.spireNamespace,
        '--no-hooks',
      ]);
    } catch (error) {
      if (!/not found|no deployed releases/i.test(error.message)) {
        this.log(`Warning: could not uninstall spire chart: ${error.message}`, 'warn');
      }
    }

    // 3. Uninstall spire-crds Helm chart
    try {
      await CommandRunner.run('helm', [
        ...helmCtxArgs,
        'uninstall',
        'spire-crds',
        '-n',
        this.spireNamespace,
        '--no-hooks',
      ]);
    } catch (error) {
      if (!/not found|no deployed releases/i.test(error.message)) {
        this.log(`Warning: could not uninstall spire-crds chart: ${error.message}`, 'warn');
      }
    }

    // 4. Force-delete lingering pods first. Pods left by the uninstalled charts (e.g.
    // spiffe-oidc-discovery-provider, finishing Completed) get stuck and block namespace
    // finalization indefinitely - delete namespace then hangs forever on "unexpected items
    // still remain ... for gvr: /v1, Resource=pods".
    try {
      await KubernetesHelper.kubectl(
        [
          ...ctxArgs,
          'delete',
          'pods',
          '--all',
          '-n',
          this.spireNamespace,
          '--force',
          '--grace-period=0',
          '--ignore-not-found=true',
        ],
        { spinner: this.spinner }
      );
    } catch {
      // best effort
    }

    // 5. Delete namespace
    try {
      await KubernetesHelper.kubectl(
        [...ctxArgs, 'delete', 'namespace', this.spireNamespace, '--ignore-not-found=true'],
        { spinner: this.spinner }
      );
    } catch {
      // best effort
    }

    this.log('SPIRE cleaned up', 'success');
  }
}
